stages:
  - build

variables:
  BUILD_DIR: "build"

build_x86:
  stage: build
  image: rust:latest  
  script:
    - mkdir -p $BUILD_DIR
    - cargo build --release
    - mv target/release/lms $BUILD_DIR/lms_x86
  artifacts:
    paths:
      - $BUILD_DIR/lms_x86
  only:
    - main

