#!/usr/bin/env python3

import os
import shutil
from typing import NoReturn
import subprocess
import platform

REPO_URL = "https://github.com/GertJan84/lms-rust-cli/releases/latest/download/lms"

def die(message: str) -> NoReturn:
    """
    Quit program with error.

    Args:
        message (str): The error message to display before exiting.
    """
    print(message)
    exit(1)


def lprint(message: str) -> None:
    """
    Lazy print with format.

    Args:
        message (str): The message to print.
    """
    print(f"{message} ...", end="", flush=True)


def execute(commands: list[str], err_message: str) -> None:
    """
    Execute a list of commands.

    Args:
        commands (list[str]): A list of commands to execute.
        message (str): A message to display in case of failure.

    Returns:
        None

    Note:
        This function runs the specified commands using subprocess.run().
        It redirects the standard output and standard error streams to DEVNULL,
        and does not raise an exception if the process returns a non-zero exit status.
        If the process returns a non-zero exit status, it calls the die() function with the provided message.
    """
    process_exe = subprocess.run(
        commands,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )

    if process_exe == 1:  # type: ignore
        die(err_message)

def is_installed(command: str, err_message: str) -> None | NoReturn:
    if not shutil.which(command):
        die(err_message)


def main():
    print(r"""
                             /$$       /$$      /$$  /$$$$$$ 
                            | $$      | $$$    /$$$ /$$__  $$
                            | $$      | $$$$  /$$$$| $$  \__/
                            | $$      | $$ $$/$$ $$|  $$$$$$ 
                            | $$      | $$  $$$| $$ \____  $$
                            | $$      | $$\  $ | $$ /$$  \ $$
                            | $$$$$$$$| $$ \/  | $$|  $$$$$$/
                            |________/|__/     |__/ \______/ 
                                 
    """)

    exe_name = ""

    match platform.system():
        case "Darwin":
            exe_name = "mac_arm64"
        case "linux":
            exe_name = "linux_64"
        case _:
            die(f"Your platform is not supported :{platform.system()}")

    is_installed("curl", "You need to have curl installed")

    lprint("Downloading")
    os.makedirs(os.path.expanduser("~/.local/bin"), exist_ok=True)

    execute(["curl", f"{REPO_URL}_{exe_name}", "-o", "~/.local/bin"], "Cant find curl")
    print(" done")

    if path := os.getenv("PATH"):  # noqa: SIM102
        if os.path.expanduser("~/.local/bin") not in path:
            print("This system doesn't have $HOME/.local/bin in its PATH.")
            print("  Add this before running lms")

    print("\nInstallation complete")

if __name__ == "__main__":
    main()
