#!/usr/bin/env python3

import os
import shutil
from typing import NoReturn
import subprocess

REPO_URL = "https://gitlab.com/gj-535479/lms-rust-cli"
EXE_NAME = "lms"
TMP_LOC = "/tmp/lms_rust"


def main():
    if not shutil.which("git"):
        exit(1)

    if os.path.exists(TMP_LOC):
        shutil.rmtree(TMP_LOC)

    os.makedirs(TMP_LOC, exist_ok=True)

    process_exe = subprocess.run(
        ["git", "clone", REPO_URL, TMP_LOC],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )

    if process_exe == 1:
        exit(1)

    process_exe = subprocess.run(
        ["cargo", "build", "--release", "--quiet"],
        cwd=TMP_LOC,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )

    if process_exe == 1:
        exit(1)

    os.makedirs(os.path.expanduser("~/.local/bin"), exist_ok=True)

    # Remove old version (needed because copy otherwise won't work)
    os.remove(os.path.expanduser(f"~/.local/bin/{EXE_NAME}"))

    shutil.copy(
        os.path.join(TMP_LOC, "target", "release", EXE_NAME),
        os.path.expanduser(f"~/.local/bin/{EXE_NAME}"),
    )


    shutil.rmtree(TMP_LOC, ignore_errors=True)


if __name__ == "__main__":
    main()
